/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRecruiterRouteImport } from './routes/app.recruiter'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppCandidateRouteImport } from './routes/app.candidate'
import { Route as AppRecruiterPipelineRouteImport } from './routes/app.recruiter.pipeline'
import { Route as AppRecruiterJobsRouteImport } from './routes/app.recruiter.jobs'
import { Route as AppRecruiterInterviewsRouteImport } from './routes/app.recruiter.interviews'
import { Route as AppRecruiterDashboardRouteImport } from './routes/app.recruiter.dashboard'
import { Route as AppRecruiterCandidatesRouteImport } from './routes/app.recruiter.candidates'
import { Route as AppRecruiterAnalyticsRouteImport } from './routes/app.recruiter.analytics'
import { Route as AppRecruiterAiAssistantRouteImport } from './routes/app.recruiter.ai-assistant'
import { Route as AppCandidateResumeBuilderRouteImport } from './routes/app.candidate.resume-builder'
import { Route as AppCandidateResumeRouteImport } from './routes/app.candidate.resume'
import { Route as AppCandidateJobsRouteImport } from './routes/app.candidate.jobs'
import { Route as AppCandidateInterviewsRouteImport } from './routes/app.candidate.interviews'
import { Route as AppCandidateInterviewStudioRouteImport } from './routes/app.candidate.interview-studio'
import { Route as AppCandidateDashboardRouteImport } from './routes/app.candidate.dashboard'
import { Route as AppCandidateCareerRouteImport } from './routes/app.candidate.career'
import { Route as AppCandidateApplicationsRouteImport } from './routes/app.candidate.applications'
import { Route as AppRecruiterJobsIdRouteImport } from './routes/app.recruiter.jobs.$id'
import { Route as AppRecruiterCandidatesIdRouteImport } from './routes/app.recruiter.candidates.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterRoute = AppRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateRoute = AppCandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruiterPipelineRoute = AppRecruiterPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterJobsRoute = AppRecruiterJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterInterviewsRoute = AppRecruiterInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterDashboardRoute = AppRecruiterDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterCandidatesRoute = AppRecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterAnalyticsRoute = AppRecruiterAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppRecruiterAiAssistantRoute = AppRecruiterAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRecruiterRoute,
} as any)
const AppCandidateResumeBuilderRoute =
  AppCandidateResumeBuilderRouteImport.update({
    id: '/resume-builder',
    path: '/resume-builder',
    getParentRoute: () => AppCandidateRoute,
  } as any)
const AppCandidateResumeRoute = AppCandidateResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppCandidateRoute,
} as any)
const AppCandidateJobsRoute = AppCandidateJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppCandidateRoute,
} as any)
const AppCandidateInterviewsRoute = AppCandidateInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AppCandidateRoute,
} as any)
const AppCandidateInterviewStudioRoute =
  AppCandidateInterviewStudioRouteImport.update({
    id: '/interview-studio',
    path: '/interview-studio',
    getParentRoute: () => AppCandidateRoute,
  } as any)
const AppCandidateDashboardRoute = AppCandidateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppCandidateRoute,
} as any)
const AppCandidateCareerRoute = AppCandidateCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AppCandidateRoute,
} as any)
const AppCandidateApplicationsRoute =
  AppCandidateApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AppCandidateRoute,
  } as any)
const AppRecruiterJobsIdRoute = AppRecruiterJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRecruiterJobsRoute,
} as any)
const AppRecruiterCandidatesIdRoute =
  AppRecruiterCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AppRecruiterCandidatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/candidate': typeof AppCandidateRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recruiter': typeof AppRecruiterRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/candidate/applications': typeof AppCandidateApplicationsRoute
  '/app/candidate/career': typeof AppCandidateCareerRoute
  '/app/candidate/dashboard': typeof AppCandidateDashboardRoute
  '/app/candidate/interview-studio': typeof AppCandidateInterviewStudioRoute
  '/app/candidate/interviews': typeof AppCandidateInterviewsRoute
  '/app/candidate/jobs': typeof AppCandidateJobsRoute
  '/app/candidate/resume': typeof AppCandidateResumeRoute
  '/app/candidate/resume-builder': typeof AppCandidateResumeBuilderRoute
  '/app/recruiter/ai-assistant': typeof AppRecruiterAiAssistantRoute
  '/app/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/app/recruiter/candidates': typeof AppRecruiterCandidatesRouteWithChildren
  '/app/recruiter/dashboard': typeof AppRecruiterDashboardRoute
  '/app/recruiter/interviews': typeof AppRecruiterInterviewsRoute
  '/app/recruiter/jobs': typeof AppRecruiterJobsRouteWithChildren
  '/app/recruiter/pipeline': typeof AppRecruiterPipelineRoute
  '/app/recruiter/candidates/$id': typeof AppRecruiterCandidatesIdRoute
  '/app/recruiter/jobs/$id': typeof AppRecruiterJobsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/candidate': typeof AppCandidateRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recruiter': typeof AppRecruiterRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app': typeof AppIndexRoute
  '/app/candidate/applications': typeof AppCandidateApplicationsRoute
  '/app/candidate/career': typeof AppCandidateCareerRoute
  '/app/candidate/dashboard': typeof AppCandidateDashboardRoute
  '/app/candidate/interview-studio': typeof AppCandidateInterviewStudioRoute
  '/app/candidate/interviews': typeof AppCandidateInterviewsRoute
  '/app/candidate/jobs': typeof AppCandidateJobsRoute
  '/app/candidate/resume': typeof AppCandidateResumeRoute
  '/app/candidate/resume-builder': typeof AppCandidateResumeBuilderRoute
  '/app/recruiter/ai-assistant': typeof AppRecruiterAiAssistantRoute
  '/app/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/app/recruiter/candidates': typeof AppRecruiterCandidatesRouteWithChildren
  '/app/recruiter/dashboard': typeof AppRecruiterDashboardRoute
  '/app/recruiter/interviews': typeof AppRecruiterInterviewsRoute
  '/app/recruiter/jobs': typeof AppRecruiterJobsRouteWithChildren
  '/app/recruiter/pipeline': typeof AppRecruiterPipelineRoute
  '/app/recruiter/candidates/$id': typeof AppRecruiterCandidatesIdRoute
  '/app/recruiter/jobs/$id': typeof AppRecruiterJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/candidate': typeof AppCandidateRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/recruiter': typeof AppRecruiterRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/app/': typeof AppIndexRoute
  '/app/candidate/applications': typeof AppCandidateApplicationsRoute
  '/app/candidate/career': typeof AppCandidateCareerRoute
  '/app/candidate/dashboard': typeof AppCandidateDashboardRoute
  '/app/candidate/interview-studio': typeof AppCandidateInterviewStudioRoute
  '/app/candidate/interviews': typeof AppCandidateInterviewsRoute
  '/app/candidate/jobs': typeof AppCandidateJobsRoute
  '/app/candidate/resume': typeof AppCandidateResumeRoute
  '/app/candidate/resume-builder': typeof AppCandidateResumeBuilderRoute
  '/app/recruiter/ai-assistant': typeof AppRecruiterAiAssistantRoute
  '/app/recruiter/analytics': typeof AppRecruiterAnalyticsRoute
  '/app/recruiter/candidates': typeof AppRecruiterCandidatesRouteWithChildren
  '/app/recruiter/dashboard': typeof AppRecruiterDashboardRoute
  '/app/recruiter/interviews': typeof AppRecruiterInterviewsRoute
  '/app/recruiter/jobs': typeof AppRecruiterJobsRouteWithChildren
  '/app/recruiter/pipeline': typeof AppRecruiterPipelineRoute
  '/app/recruiter/candidates/$id': typeof AppRecruiterCandidatesIdRoute
  '/app/recruiter/jobs/$id': typeof AppRecruiterJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/candidate'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recruiter'
    | '/app/settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/app/candidate/applications'
    | '/app/candidate/career'
    | '/app/candidate/dashboard'
    | '/app/candidate/interview-studio'
    | '/app/candidate/interviews'
    | '/app/candidate/jobs'
    | '/app/candidate/resume'
    | '/app/candidate/resume-builder'
    | '/app/recruiter/ai-assistant'
    | '/app/recruiter/analytics'
    | '/app/recruiter/candidates'
    | '/app/recruiter/dashboard'
    | '/app/recruiter/interviews'
    | '/app/recruiter/jobs'
    | '/app/recruiter/pipeline'
    | '/app/recruiter/candidates/$id'
    | '/app/recruiter/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/candidate'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recruiter'
    | '/app/settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app'
    | '/app/candidate/applications'
    | '/app/candidate/career'
    | '/app/candidate/dashboard'
    | '/app/candidate/interview-studio'
    | '/app/candidate/interviews'
    | '/app/candidate/jobs'
    | '/app/candidate/resume'
    | '/app/candidate/resume-builder'
    | '/app/recruiter/ai-assistant'
    | '/app/recruiter/analytics'
    | '/app/recruiter/candidates'
    | '/app/recruiter/dashboard'
    | '/app/recruiter/interviews'
    | '/app/recruiter/jobs'
    | '/app/recruiter/pipeline'
    | '/app/recruiter/candidates/$id'
    | '/app/recruiter/jobs/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/candidate'
    | '/app/notifications'
    | '/app/profile'
    | '/app/recruiter'
    | '/app/settings'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/'
    | '/app/candidate/applications'
    | '/app/candidate/career'
    | '/app/candidate/dashboard'
    | '/app/candidate/interview-studio'
    | '/app/candidate/interviews'
    | '/app/candidate/jobs'
    | '/app/candidate/resume'
    | '/app/candidate/resume-builder'
    | '/app/recruiter/ai-assistant'
    | '/app/recruiter/analytics'
    | '/app/recruiter/candidates'
    | '/app/recruiter/dashboard'
    | '/app/recruiter/interviews'
    | '/app/recruiter/jobs'
    | '/app/recruiter/pipeline'
    | '/app/recruiter/candidates/$id'
    | '/app/recruiter/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recruiter': {
      id: '/app/recruiter'
      path: '/recruiter'
      fullPath: '/app/recruiter'
      preLoaderRoute: typeof AppRecruiterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidate': {
      id: '/app/candidate'
      path: '/candidate'
      fullPath: '/app/candidate'
      preLoaderRoute: typeof AppCandidateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recruiter/pipeline': {
      id: '/app/recruiter/pipeline'
      path: '/pipeline'
      fullPath: '/app/recruiter/pipeline'
      preLoaderRoute: typeof AppRecruiterPipelineRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/jobs': {
      id: '/app/recruiter/jobs'
      path: '/jobs'
      fullPath: '/app/recruiter/jobs'
      preLoaderRoute: typeof AppRecruiterJobsRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/interviews': {
      id: '/app/recruiter/interviews'
      path: '/interviews'
      fullPath: '/app/recruiter/interviews'
      preLoaderRoute: typeof AppRecruiterInterviewsRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/dashboard': {
      id: '/app/recruiter/dashboard'
      path: '/dashboard'
      fullPath: '/app/recruiter/dashboard'
      preLoaderRoute: typeof AppRecruiterDashboardRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/candidates': {
      id: '/app/recruiter/candidates'
      path: '/candidates'
      fullPath: '/app/recruiter/candidates'
      preLoaderRoute: typeof AppRecruiterCandidatesRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/analytics': {
      id: '/app/recruiter/analytics'
      path: '/analytics'
      fullPath: '/app/recruiter/analytics'
      preLoaderRoute: typeof AppRecruiterAnalyticsRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/recruiter/ai-assistant': {
      id: '/app/recruiter/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/app/recruiter/ai-assistant'
      preLoaderRoute: typeof AppRecruiterAiAssistantRouteImport
      parentRoute: typeof AppRecruiterRoute
    }
    '/app/candidate/resume-builder': {
      id: '/app/candidate/resume-builder'
      path: '/resume-builder'
      fullPath: '/app/candidate/resume-builder'
      preLoaderRoute: typeof AppCandidateResumeBuilderRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/candidate/resume': {
      id: '/app/candidate/resume'
      path: '/resume'
      fullPath: '/app/candidate/resume'
      preLoaderRoute: typeof AppCandidateResumeRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/candidate/jobs': {
      id: '/app/candidate/jobs'
      path: '/jobs'
      fullPath: '/app/candidate/jobs'
      preLoaderRoute: typeof AppCandidateJobsRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/candidate/interviews': {
      id: '/app/candidate/interviews'
      path: '/interviews'
      fullPath: '/app/candidate/interviews'
      preLoaderRoute: typeof AppCandidateInterviewsRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/candidate/interview-studio': {
      id: '/app/candidate/interview-studio'
      path: '/interview-studio'
      fullPath: '/app/candidate/interview-studio'
      preLoaderRoute: typeof AppCandidateInterviewStudioRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/candidate/dashboard': {
      id: '/app/candidate/dashboard'
      path: '/dashboard'
      fullPath: '/app/candidate/dashboard'
      preLoaderRoute: typeof AppCandidateDashboardRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/candidate/career': {
      id: '/app/candidate/career'
      path: '/career'
      fullPath: '/app/candidate/career'
      preLoaderRoute: typeof AppCandidateCareerRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/candidate/applications': {
      id: '/app/candidate/applications'
      path: '/applications'
      fullPath: '/app/candidate/applications'
      preLoaderRoute: typeof AppCandidateApplicationsRouteImport
      parentRoute: typeof AppCandidateRoute
    }
    '/app/recruiter/jobs/$id': {
      id: '/app/recruiter/jobs/$id'
      path: '/$id'
      fullPath: '/app/recruiter/jobs/$id'
      preLoaderRoute: typeof AppRecruiterJobsIdRouteImport
      parentRoute: typeof AppRecruiterJobsRoute
    }
    '/app/recruiter/candidates/$id': {
      id: '/app/recruiter/candidates/$id'
      path: '/$id'
      fullPath: '/app/recruiter/candidates/$id'
      preLoaderRoute: typeof AppRecruiterCandidatesIdRouteImport
      parentRoute: typeof AppRecruiterCandidatesRoute
    }
  }
}

interface AppCandidateRouteChildren {
  AppCandidateApplicationsRoute: typeof AppCandidateApplicationsRoute
  AppCandidateCareerRoute: typeof AppCandidateCareerRoute
  AppCandidateDashboardRoute: typeof AppCandidateDashboardRoute
  AppCandidateInterviewStudioRoute: typeof AppCandidateInterviewStudioRoute
  AppCandidateInterviewsRoute: typeof AppCandidateInterviewsRoute
  AppCandidateJobsRoute: typeof AppCandidateJobsRoute
  AppCandidateResumeRoute: typeof AppCandidateResumeRoute
  AppCandidateResumeBuilderRoute: typeof AppCandidateResumeBuilderRoute
}

const AppCandidateRouteChildren: AppCandidateRouteChildren = {
  AppCandidateApplicationsRoute: AppCandidateApplicationsRoute,
  AppCandidateCareerRoute: AppCandidateCareerRoute,
  AppCandidateDashboardRoute: AppCandidateDashboardRoute,
  AppCandidateInterviewStudioRoute: AppCandidateInterviewStudioRoute,
  AppCandidateInterviewsRoute: AppCandidateInterviewsRoute,
  AppCandidateJobsRoute: AppCandidateJobsRoute,
  AppCandidateResumeRoute: AppCandidateResumeRoute,
  AppCandidateResumeBuilderRoute: AppCandidateResumeBuilderRoute,
}

const AppCandidateRouteWithChildren = AppCandidateRoute._addFileChildren(
  AppCandidateRouteChildren,
)

interface AppRecruiterCandidatesRouteChildren {
  AppRecruiterCandidatesIdRoute: typeof AppRecruiterCandidatesIdRoute
}

const AppRecruiterCandidatesRouteChildren: AppRecruiterCandidatesRouteChildren =
  {
    AppRecruiterCandidatesIdRoute: AppRecruiterCandidatesIdRoute,
  }

const AppRecruiterCandidatesRouteWithChildren =
  AppRecruiterCandidatesRoute._addFileChildren(
    AppRecruiterCandidatesRouteChildren,
  )

interface AppRecruiterJobsRouteChildren {
  AppRecruiterJobsIdRoute: typeof AppRecruiterJobsIdRoute
}

const AppRecruiterJobsRouteChildren: AppRecruiterJobsRouteChildren = {
  AppRecruiterJobsIdRoute: AppRecruiterJobsIdRoute,
}

const AppRecruiterJobsRouteWithChildren =
  AppRecruiterJobsRoute._addFileChildren(AppRecruiterJobsRouteChildren)

interface AppRecruiterRouteChildren {
  AppRecruiterAiAssistantRoute: typeof AppRecruiterAiAssistantRoute
  AppRecruiterAnalyticsRoute: typeof AppRecruiterAnalyticsRoute
  AppRecruiterCandidatesRoute: typeof AppRecruiterCandidatesRouteWithChildren
  AppRecruiterDashboardRoute: typeof AppRecruiterDashboardRoute
  AppRecruiterInterviewsRoute: typeof AppRecruiterInterviewsRoute
  AppRecruiterJobsRoute: typeof AppRecruiterJobsRouteWithChildren
  AppRecruiterPipelineRoute: typeof AppRecruiterPipelineRoute
}

const AppRecruiterRouteChildren: AppRecruiterRouteChildren = {
  AppRecruiterAiAssistantRoute: AppRecruiterAiAssistantRoute,
  AppRecruiterAnalyticsRoute: AppRecruiterAnalyticsRoute,
  AppRecruiterCandidatesRoute: AppRecruiterCandidatesRouteWithChildren,
  AppRecruiterDashboardRoute: AppRecruiterDashboardRoute,
  AppRecruiterInterviewsRoute: AppRecruiterInterviewsRoute,
  AppRecruiterJobsRoute: AppRecruiterJobsRouteWithChildren,
  AppRecruiterPipelineRoute: AppRecruiterPipelineRoute,
}

const AppRecruiterRouteWithChildren = AppRecruiterRoute._addFileChildren(
  AppRecruiterRouteChildren,
)

interface AppRouteChildren {
  AppCandidateRoute: typeof AppCandidateRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecruiterRoute: typeof AppRecruiterRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidateRoute: AppCandidateRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecruiterRoute: AppRecruiterRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
